### ISSUE TITLE
I'm not what your Looking for :)

### ISSUE THREAD

**Issue by ghost** [ZoeLi00/FAQ#1]

**Comment by ZoeLi00** [comment]
Hi, Pasipac

You're the first guy who sends the email to you and I really appreciate
about that.
It's totally fine that you didn't tick all the boxes.
Since you prefer writing in English, maybe we can communicate with each
other via email.
But I would not oppose to see you some day.
BTW, would you mind to tell me more about yourself?
such as:
What are you looking for?
How to introduce yourself to me in a simple way?
What do you like?
Why you visited Europe? Where are you from?
...
You can share anything you want to me.
Oh, a picture would be helpful for me to visualize you.
Have a nice day:)




pasipac <notifications@github.com> 于2021年1月11日周一 下午3:44写道：
